ERROR - 2021-12-22 20:50:16 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-12-22 20:50:16 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
#0 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT `categor...', Array, false)
#2 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/Model.php(723): CodeIgniter\Database\BaseBuilder->get()
#3 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/app/Models/CategoriesModel.php(17): CodeIgniter\Model->__call('get', Array)
#4 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/app/Controllers/Frontend/HomeController.php(20): App\Models\CategoriesModel->getCategories()
#5 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/CodeIgniter.php(824): App\Controllers\Frontend\HomeController->index()
#6 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Frontend\HomeController))
#7 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 /home/programmer/Documents/Developments/Codeigniter/Projects/putra-ecommerce/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/home/programme...')
#10 {main}
